import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://std-cm-test.iconcm.com/');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('icon001');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('link', { name: 'ระบบจัดการข้อมูลกลาง' }).click();
  await page.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page.getByRole('link', { name: ' Setup Group Model Type' }).click();
  await page.getByRole('link', { name: ' Setup Project & Department' }).click();
  await page.getByRole('link', { name: ' Setup Approve' }).click();
  await page.locator('a').filter({ hasText: 'BOM (10)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'BOQ (1)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Cost Control (2)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Adjust Budget (22)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Requisition (3)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Requisition Decrement (4)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order (5)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Advance' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Decrement (7)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Work Order (8)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Work Order Decrement (23)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Progress Subcontrator (9)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Contract Close (11)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Petty Cash (13)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Receive (15)' }).click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByText('Debit Note / Credit Note (18)').click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page.getByText('Issue (20)').click();
  await page.getByLabel('Filter:').click();
  await page.getByLabel('Filter:').fill('icon001');
  await page.getByRole('gridcell', { name: '      ' }).locator('a').nth(2).click();
  await page.getByRole('button', { name: 'Yes, delete it!' }).click();
});