import { test, expect, chromium } from '@playwright/test';

test('test', async () => {
   const browser =  await chromium.launch();
 const context = await browser.newContext()
 const page5 =await context.newPage();
 await page5.locator('a').filter({ hasText: 'Cost Control' }).click();
 await page5.getByRole('link', { name: ' Setup Cost Center' }).click();
 await page5.getByPlaceholder('Search ').click();
 await page5.getByPlaceholder('Search ').fill('CA');
 await page5.getByRole('button', { name: '' }).click();
 await page5.getByPlaceholder('Search ').click();
 await page5.getByPlaceholder('Search ').click();
 await page5.getByPlaceholder('Search ').fill('M');
 await page5.getByRole('button', { name: '' }).click();
 await page5.getByRole('button', { name: ' Add' }).click();
 await page5.locator('#cgroup_code').click();
 await page5.locator('#cgroup_code').fill('MM');
 await page5.locator('#cgroup_name').click();
 await page5.locator('#cgroup_name').fill('construction');
 await page5.locator('#costcode_d').selectOption('2');
 await page5.getByRole('button', { name: '' }).nth(1).click();
 await page5.getByText('Showing 0 to 0 of 0 entries←→').click();
 await page5.getByRole('button', { name: '' }).nth(1).click();
 await page5.locator('#get_head').click();
 await page5.locator('#get_head').click();
 await page5.locator('#get_head').click();
 await page5.locator('#get_head').getByLabel('Close').click();
 await page5.locator('#head_de_H').check();
 await page5.locator('#level').selectOption('1');
 await page5.locator('#new_pay').getByRole('button', { name: '' }).click();
 await page5.locator('#get_head').getByLabel('Close').click();
 await page5.getByText('Save').click();
 await page5.getByRole('button', { name: 'OK' }).click();
 await page5.getByRole('button', { name: 'OK' }).click();
 await page5.getByPlaceholder('Username').click();
await page5.getByPlaceholder('Search ').click();
await page5.getByPlaceholder('Search ').fill('M');
await page5.getByRole('button', { name: '' }).click();
await page5.getByPlaceholder('Search ').click();
await page5.getByPlaceholder('Search ').fill('MM');
await page5.getByRole('button', { name: '' }).click();
await page5.getByRole('button', { name: ' Add' }).click();
await page5.locator('#cgroup_code').click();
await page5.locator('#cgroup_code').fill('MM1');
await page5.locator('#cgroup_name').click();
await page5.locator('#cgroup_name').fill('งานก่สร้าง');
await page5.locator('#costcode_d').selectOption('2');
await page5.locator('#level').selectOption('2');
await page5.getByRole('button', { name: '' }).nth(1).click();
await page5.locator('tr').filter({ hasText: 'MM construction SELECT' }).locator('button').click();
await page5.getByRole('button', { name: '' }).nth(2).click();
await page5.getByText('11101010').click({
    button: 'right'
  });
await page5.getByText('11101010').click();
await page5.getByText('11101010').click({
    button: 'right'
  });
await page5.getByText('11101010').click();
await page5.getByText('11101010').click();
await page5.getByText('11101010').click();
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').click();
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').fill('ค่าก');
await page5.locator('tr').filter({ hasText: '730 51104001' }).locator('button').click();
await page5.locator('#basiccc_b_wrapper').getByText('Filter: Show:').click({
    button: 'right'
  });
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').fill('ค่าก่อสร้าง');
await page5.locator('tr').filter({ hasText: '110 11501390 WIP' }).locator('button').click();
await page5.locator('#open_expense_acc').click();
await page5.locator('#open_expense_acc').click();
await page5.locator('#open_expense_acc').getByText('X').click();
await page5.getByText('Save').click();
await page5.getByRole('button', { name: 'OK' }).click();
await page5.locator('#ex_lock_add1').check();
await page5.getByText('Save').click();
await page5.getByRole('button', { name: 'OK' }).click();
await page5.getByRole('link', { name: ' Setup Cost Center' }).click();
await page5.getByRole('button', { name: ' Add' }).click();
await page5.locator('#cgroup_code').click();
await page5.locator('#cgroup_code').fill('MM2');
await page5.locator('#cgroup_name').click();
await page5.locator('#cgroup_name').fill('ค่างานสาธาฯ');
await page5.locator('#costcode_d').selectOption('2');
await page5.locator('#level').selectOption('2');
await page5.getByRole('button', { name: '' }).nth(1).click();
await page5.locator('tr').filter({ hasText: 'MM construction SELECT' }).locator('button').click();
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').click();
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').fill('สาธา');
await page5.locator('tr').filter({ hasText: '91 11501240 WIP' }).locator('button').click();
await page5.locator('tr').filter({ hasText: '94 11501290 WIP' }).locator('button').click();
await page5.locator('#open_expense_acc').getByText('X').click();
await page5.getByText('Save').click();
await page5.getByRole('button', { name: 'OK' }).click();
await page5.getByRole('button', { name: ' Add' }).click();
await page5.locator('#cgroup_code').click();
await page5.locator('#cgroup_code').fill('MM3');
await page5.locator('#cgroup_name').click();
await page5.locator('#cgroup_name').fill('ค่าออกแบบ');
await page5.locator('#costcode_d').selectOption('2');
await page5.locator('#level').selectOption('1');
await page5.getByRole('button', { name: '' }).nth(1).click();
await page5.locator('#get_head').getByLabel('Close').click();
await page5.locator('#level').selectOption('2');
await page5.getByRole('button', { name: '' }).nth(1).click();
await page5.locator('tr').filter({ hasText: 'MM construction SELECT' }).locator('button').click();
await page5.getByRole('button', { name: '' }).nth(2).click();
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').click();
await page5.locator('#basiccc_b_filter').getByLabel('Filter:').fill('ออกแบบ');
await page5.locator('tr').filter({ hasText: '11501112 WIP ค่าออกแบบ SELECT' }).locator('button').click();
await page5.locator('tr').filter({ hasText: '490 52102060' }).locator('button').click();
await page5.locator('#open_expense_acc').getByText('X').click();
await page5.locator('#ex_lock_add2').check();
await page5.getByText('Save').click();
await page5.getByRole('button', { name: 'OK' }).click();
});