import { test, expect } from "@playwright/test";

test("test", async ({ page }) => {
  await page.goto('https://maison-cm-test.iconframework.com/auth/index');
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('Mtest');
  await page.getByPlaceholder('Username').press('Tab');
  await page.getByPlaceholder('Password').fill('123456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator("//i[@class='glyphicon glyphicon-log-in']");
  await page.getByRole('link', { name: 'ระบบจัดการข้อมูลกลาง' }).click();
  await page.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page.getByRole('link', { name: ' Setup Project & Department' }).click();
  await page.getByRole('link', { name: ' Setup Approve' }).click();
  await page.locator('a').filter({ hasText: 'BOM (10)' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle181 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'BOQ (1)' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle182 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Cost Control (2)' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle183 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Adjust Budget (22)' }).click();
  await page.getByRole('gridcell', { name: '      ' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle184 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Requisition (3)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Purchase Requisition Decrement (4)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Purchase Requisition (3)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle185 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Requisition Decrement (4)' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle186 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order (5)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Purchase Order Advance' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Purchase Order Decrement (7)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Purchase Order (5)' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Advance' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Decrement (7)' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order (5)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle187 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Advance' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle188 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Decrement (7)' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle189 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Work Order (8)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Work Order Decrement (23)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Advance' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Decrement (7)' }).click();
  await page.locator('a').filter({ hasText: 'Work Order Decrement (23)' }).click();
  await page.locator('a').filter({ hasText: 'Progress Subcontrator (9)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Contract Close (11)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Add Row NO. LV. Cost Action').click();
  await page.locator('#department').selectOption('PPA005');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Work Order (8)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle190 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Work Order Decrement (23)' }).click();
  await page.getByRole('gridcell', { name: '      ' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle191 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Progress Subcontrator (9)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle192 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Contract Close (11)' }).click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle193 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Petty Cash (13)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Petty Cash (13)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle194 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Receive (15)' }).click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('test');
  await page.locator('#department').selectOption('PPA005');
  await page.getByText('Save Group').click();
  await page.locator('a').filter({ hasText: 'Purchase Order Receive (15)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle195 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Debit Note / Credit Note (18)').click();
  await page.getByText('Add Group').click();
  await page.getByText('Department : *').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Mtest');
  await page.locator('#department').selectOption('PPA005');
  await page.getByText('Save Group').click();
  await page.getByText('Issue (20)').click();
  await page.getByText('Add Group').click();
  await page.locator('#groupname').click();
  await page.locator('#groupname').fill('Test');
  await page.locator('#groupname').press('ArrowLeft');
  await page.locator('#groupname').press('ArrowLeft');
  await page.locator('#groupname').press('ArrowLeft');
  await page.locator('#groupname').fill('Mtest');
  await page.getByText('Save Group').click();
  await page.getByText('Issue (20)').click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle197 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Debit Note / Credit Note (18)').click();
  await page.getByRole('row', { name: '5 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('#addjobtitle').click();
  await page.locator('#newjobtitle196 a').first().click();
  await page.getByLabel('Search:').click();
  await page.getByLabel('Search:').fill('m');
  await page.getByRole('row', { name: 'Mtest | Mtest SELECT' }).getByRole('button').click();
  await page.getByText('Save', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order Receive (15)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).getByRole('gridcell').nth(2).click();
  await page.getByRole('button', { name: ' Close' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('a').filter({ hasText: 'Petty Cash (13)' }).click();
  await page.locator('a').filter({ hasText: 'Work Order (8)' }).click();
  await page.locator('a').filter({ hasText: 'Purchase Order (5)' }).click();
  await page.getByRole('row', { name: '6 Department : ( PPA005 )' }).locator('a').first().click();
  await page.locator('.panel-body').first().click();

 });
// await page.getByPlaceholder('Username').click();
//   await page.getByPlaceholder('Username').fill('Mtest');
//   await page.getByPlaceholder('Password').click();
//   await page.getByPlaceholder('Password').fill('123456');
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.getByRole('link', { name: '' }).click();
//   await page.getByRole('link', { name: 'ระบบจัดการข้อมูลกลาง' }).click();
//   await page.locator('a').filter({ hasText: 'Genaral Settings' }).click();
//   await page.getByRole('link', { name: ' Setup Project Type' }).click();
//   await page.getByRole('link', { name: ' Setup Project & Department' }).click();
//   await page.getByRole('link', { name: ' Setup Approve' }).click();
//   await page.locator('a').filter({ hasText: 'BOM (10)' }).click();
//   await page.getByText('Add Group').click();
//   await page.locator('#groupname').click();
//   await page.locator('#groupname').fill('M-test');
//   await page.locator('#department').selectOption('PPA005');
//   await page.getByText('Save Group').click();
//   await page.locator('a').filter({ hasText: 'BOQ (1)' }).click();
//   await page.getByText('Add Group').click();
//   await page.locator('#groupname').click();
//   await page.locator('#groupname').fill('Mtest');
//   await page.locator('#department').selectOption('PPA005');
//   await page.getByText('Save Group').click();
//   await page.locator('a').filter({ hasText: 'Cost Control (2)' }).click();
//   await page.getByText('Add Group').click();
//   await page.locator('#groupname').click();
//   await page.locator('#groupname').fill('Mtest');
//   await page.locator('#department').selectOption('PPA005');
//   await page.getByText('Save Group').click();
//   await page.locator('a').filter({ hasText: 'Adjust Budget (22)' }).click();
//   await page.getByText('Add Group').click();
//   await page.locator('#groupname').click();
//   await page.locator('#groupname').fill('Mtest');
//   await page.locator('#department').selectOption('PPA005');
//   await page.getByText('Save Group').click();
//   await page.locator('a').filter({ hasText: 'BOM (10)' }).click();
//   await page.getByText('Department : ( PPA005 ) Name').click();
//   await page.getByText('Department : ( PPA005 ) Name').click();


