import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://maison-cm-test.iconframework.com/auth/index');

  await page.getByPlaceholder('Username').click();
  await page.getByPlaceholder('Username').fill('Mtest');
  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('123456');
  await page.getByPlaceholder('Password').press('Enter');
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('link', { name: 'ระบบจัดการข้อมูลกลาง' }).click();
  await page.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page.getByRole('link', { name: ' Setup Permission' }).click();
  await page.getByRole('link', { name: ' Permission by User' }).click();
  await page.getByPlaceholder('Type to filter...').click();
  await page.getByPlaceholder('Type to filter...').fill('m');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).locator('#modalcompany').click();
  const page1 = await page1Promise;
  await page1.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page1.getByRole('link', { name: ' Setup Project Type' }).click();
  await page1.getByRole('button', { name: ' New' }).click();
  await page1.locator('#code').click();
  await page1.locator('#code').fill('IM');
  await page1.getByText('Code : * Name : * Type : Low-').click();
  await page1.locator('#name').click();
  await page1.locator('#name').fill('Icon-M');
  await page1.getByRole('button', { name: ' Save' }).click();
  await page1.getByRole('button', { name: 'OK' }).click();
  await page1.getByRole('link', { name: ' Setup Permission' }).click();
  await page1.getByRole('link', { name: ' Permission by User' }).click();
  await page1.getByPlaceholder('Type to filter...').click();
  await page1.getByPlaceholder('Type to filter...').fill('m');
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).locator('#modalcompany').click();
  const page2 = await page2Promise;
  await page2.getByRole('button', { name: 'Project' }).click();
  await page2.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page2.getByRole('link', { name: ' Setup Project & Department' }).click();
  await page2.getByRole('link', { name: ' Setup Project Type' }).click();
  await page2.locator('#new_item8').click();
  await page2.getByRole('button', { name: 'X' }).click();
  await page2.getByRole('link', { name: ' Setup Project & Department' }).click();
  await page2.getByRole('link', { name: ' Setup Company' }).click();
  await page2.getByRole('link', { name: ' Setup Permission' }).click();
  await page2.getByRole('link', { name: ' Permission by User' }).click();
  await page2.getByPlaceholder('Type to filter...').click();
  await page2.getByPlaceholder('Type to filter...').fill('m');
  await page2.getByTitle('Setup User Report').nth(4).click();
  await page2.getByRole('button', { name: 'Close' }).click();
  await page2.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).getByRole('link').click();
  await page2.locator('.main_module').first().check();
  await page2.locator('td:nth-child(3) > .main_module').first().check();
  await page2.locator('tr:nth-child(163) > td:nth-child(2) > .main_module').check();
  await page2.locator('tr:nth-child(163) > td:nth-child(3) > .main_module').check();
  await page2.locator('tr:nth-child(163) > td:nth-child(4) > .main_module').check();
  await page2.locator('tr:nth-child(163) > td:nth-child(5) > .main_module').check();
  await page2.locator('tr:nth-child(163) > td:nth-child(6) > .main_module').check();
  await page2.locator('tr:nth-child(163) > td:nth-child(7) > .main_module').check();
  await page2.getByRole('link', { name: ' Setup Permission' }).click();
  await page2.getByRole('link', { name: ' Permission by User' }).click();
  await page2.getByPlaceholder('Type to filter...').click();
  await page2.getByPlaceholder('Type to filter...').fill('m');
  const page3Promise = page2.waitForEvent('popup');
  await page2.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).locator('#modalcompany').click();
  const page3 = await page3Promise;
  await page3.getByRole('button', { name: 'Project' }).click();
  await page3.getByRole('button', { name: 'Department' }).click();
  await page3.getByRole('button', { name: 'Project' }).click();
  await page3.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page3.getByRole('link', { name: ' Setup Project Unit' }).click();
  await page3.getByRole('link', { name: ' Setup Project Type' }).click();
  await page3.getByRole('link', { name: ' Setup Project & Department' }).click();
  await page3.goto('https://maison-cm-test.iconframework.com/data_master/setup_project_main/1/1/69');// มองไม่เห็น ตัวโปรเจค ในหน้านี้
  await page3.getByRole('link', { name: ' New' }).click();
  await page3.getByPlaceholder('Code').click();
  await page3.getByPlaceholder('Code').fill('IM');
  await page3.getByPlaceholder('Name', { exact: true }).click();
  await page3.getByPlaceholder('Name', { exact: true }).fill('Icon-M1');
  await page3.locator('#startproject').fill('2024-06-01');
  await page3.getByPlaceholder('Name', { exact: true }).click();
  await page3.getByPlaceholder('Name', { exact: true }).click();
  await page3.getByPlaceholder('Name', { exact: true }).click();
  await page3.getByPlaceholder('Name Eng').click();
  await page3.getByPlaceholder('Name Eng').fill('Icon-M1');
  await page3.getByLabel('Yes').check();
  await page3.locator('#pjtype').selectOption('IM');
  await page3.getByRole('link', { name: 'Admin' }).click();
  await page3.getByRole('button', { name: ' เพิ่มผู้ดูแล' }).click();
  await page3.locator('input[name="adminname2\\[\\]"]').click();
  await page3.locator('input[name="adminname2\\[\\]"]').fill('add1');
  await page3.getByRole('link', { name: 'Consultants' }).click();
  await page3.getByRole('button', { name: ' เพิ่มผู้ติดต่อโครงการ' }).click();
  await page3.locator('input[name="contactname\\[\\]"]').click();
  await page3.locator('input[name="contactname\\[\\]"]').fill('add1');
  await page3.getByRole('button', { name: ' Save' }).click();
  await page3.getByRole('button', { name: 'OK' }).click();
  await page3.getByRole('link', { name: 'Admin' }).click();
  await page3.getByRole('link', { name: 'Consultants' }).click();
  await page3.getByRole('link', { name: 'Admin' }).click();
  await page3.getByRole('link', { name: 'Consultants' }).click();
  await page3.getByRole('link', { name: 'Admin' }).click();
  await page3.getByRole('button', { name: ' เพิ่มผู้ดูแล' }).click();
  await page3.locator('input[name="adminname2\\[\\]"]').click();
  await page3.locator('input[name="adminname2\\[\\]"]').fill('add1');
  await page3.getByRole('link', { name: 'Consultants' }).click();
  await page3.getByRole('button', { name: ' เพิ่มผู้ติดต่อโครงการ' }).click();
  await page3.locator('input[name="contactname\\[\\]"]').click();
  await page3.locator('input[name="contactname\\[\\]"]').fill('add1');
  await page3.getByRole('button', { name: ' Save' }).click();
  await page3.getByRole('button', { name: 'OK' }).click();
  await page3.getByRole('link', { name: ' Back' }).click();
  await page3.getByRole('row', { name: 'IM Icon-M1 Active ' }).getByRole('link').click();
  await page3.getByRole('link', { name: 'Admin' }).click();
  await page3.getByRole('link', { name: 'Consultants' }).click();
  await page3.getByRole('link', { name: ' Back' }).click();
  await page3.getByRole('link', { name: ' Setup Group Model Type' }).click();
  await page3.getByRole('link', { name: ' Setup Model Type' }).click();
  await page3.getByRole('button', { name: ' New' }).click();
  await page3.locator('#model_type_code').click();
  await page3.locator('#model_type_code').fill('MT1');
  await page3.locator('#model_type_name').click();
  await page3.locator('#model_type_name').fill('M-Type1');
  await page3.locator('#model_type_name_eng').click();
  await page3.locator('#model_type_name_eng').fill('M-Type1');
  await page3.locator('#short_name').click();
  await page3.locator('#short_name').fill('M-Type1');
  await page3.locator('#project_type').selectOption('IM');
  await page3.locator('#save_t').click();
  await page3.getByRole('button', { name: 'OK' }).click();
  await page3.getByRole('link', { name: ' Setup Model', exact: true }).click();
  await page3.getByRole('link', { name: ' Setup Phase / Building' }).click();
  await page3.getByRole('link', { name: ' Setup Model', exact: true }).click();
  await page3.getByRole('link', { name: ' Setup Permission' }).click();
  await page3.getByRole('link', { name: ' Permission by User' }).click();
  await page3.getByPlaceholder('Type to filter...').click();
  await page3.getByPlaceholder('Type to filter...').fill('m');
  await page3.getByRole('gridcell', { name: '   ' }).nth(4).click();
  const page4Promise = page3.waitForEvent('popup');
  await page3.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).locator('#modalcompany').click();
  const page4 = await page4Promise;
  await page4.getByRole('button', { name: 'Project' }).click();
  await page4.getByLabel('IM - Icon-M1').check();
  await page4.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page4.getByRole('link', { name: ' Setup Model Type' }).click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('m');
  await page4.locator('#tbTender_paginate').getByText('5').click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('');
  await page4.getByRole('link', { name: ' Setup Model Type' }).click();
  await page4.getByLabel('Filter:').click();
  await page4.getByPlaceholder('Type to filter...').fill('');
  await page4.locator('#tbTender_paginate').getByText('5').click();
  await page4.getByRole('link', { name: ' Setup Model Type' }).click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('');
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('');
  await page4.locator('#tbTender_paginate').getByText('5').click();
  await page4.locator('#tbTender_paginate').getByText('2').click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('M');
  await page4.locator('#tbTender_paginate').getByText('5').click();
  await page4.locator('#tbTender_paginate').getByText('1').click();
  await page4.getByRole('link', { name: ' Setup Model', exact: true }).click();
  await page4.getByRole('link', { name: ' Setup Project Type' }).click();
  await page4.getByRole('link', { name: ' Setup Project & Department' }).click();
  await page4.getByRole('searchbox', { name: 'Filter: ' }).click();
  await page4.getByRole('searchbox', { name: 'Filter: ' }).fill('');
  await page4.getByRole('link', { name: ' Setup Group Model Type' }).click();
  await page4.getByRole('link', { name: ' Setup Model Type' }).click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('th');
  await page4.getByPlaceholder('Type to filter...').press('Enter');
  await page4.getByPlaceholder('Type to filter...').press('Enter');
  await page4.getByPlaceholder('Type to filter...').fill('m');
  await page4.getByPlaceholder('Type to filter...').press('Enter');
  await page4.getByPlaceholder('Type to filter...').fill('mt'); // ฟิวเตอร์ "M" ไม่ขึ้น แต่ MT ขึ้น 
  await page4.getByRole('link', { name: ' Setup Model Type' }).click();
  await page4.locator('#tbTender_paginate').getByText('5').click();
  await page4.getByRole('row', { name: 'MT1 M-Type1 M-Type1 Home Active ' }).locator('a').click();
  await page4.getByRole('button', { name: ' Close' }).click();
  await page4.getByRole('link', { name: ' Setup Model', exact: true }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('button', { name: ' New' }).click();
  await page4.locator('#model_code').click();
  await page4.locator('#model_code').fill('MD1');
  await page4.locator('#model_name').click();
  await page4.locator('#model_name').fill('MD1');
  await page4.getByText('Model Code : * Model Name').click();
  await page4.locator('#modelname_eng').click();
  await page4.locator('#modelname_eng').fill('MD1');
  await page4.locator('#m_type_code').selectOption('MT1');
  await page4.locator('#model_area').click();
  await page4.locator('#model_area').fill('70.00');
  await page4.locator('#parking_amount').click();
  await page4.locator('#parking_amount').fill('60');
  await page4.getByText('Save').click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Phase / Building' }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('button', { name: ' Add' }).click();
  await page4.locator('#phase_name').click();
  await page4.locator('#phase_name').fill('MP1');
  await page4.locator('#phase_remarks').click();
  await page4.locator('#phase_remarks').fill('M-Phase1');
  await page4.locator('#PhaseNameEng').click();
  await page4.locator('#PhaseNameEng').fill('M-Phase1');
  await page4.getByRole('button', { name: ' Save' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Block / Floor' }).click();
  await page4.getByRole('gridcell', { name: ' Select' }).click();
  await page4.getByRole('button', { name: ' Add' }).click();
  await page4.locator('#block_name').click();
  await page4.locator('#block_name').fill('MB1');
  await page4.locator('#block_remarks').click();
  await page4.locator('#block_remarks').fill('M-Block1');
  await page4.getByRole('button', { name: ' Save' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Phase / Building' }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('link', { name: '' }).click();
  await page4.getByRole('button', { name: 'Select' }).click();
  await page4.getByRole('button', { name: ' Save' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Block / Floor' }).click();
  await page4.getByRole('link', { name: ' Setup Project Unit' }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('link', { name: ' New' }).click();
  await page4.locator('#unitcode').click();
  await page4.locator('#unitcode').fill('M01');
  await page4.locator('#unitname').click();
  await page4.locator('#unitname').fill('M01');
  await page4.locator('#valid_from').fill('2024-06-01');
  await page4.locator('#u_type').selectOption('MD1');
  await page4.getByRole('button', { name: '' }).first().click();
  await page4.getByText('SELECT').click();
  await page4.locator('#SellingArea').click();
  await page4.locator('#SellingArea').fill('60');
  await page4.getByRole('button', { name: '' }).nth(1).click();
  await page4.locator('#DataTables_Table_1').getByText('SELECT').click();
  await page4.locator('#valid_to').fill('2024-07-31');
  await page4.locator('#AssetType').selectOption('4');
  await page4.getByText('Save').click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Project Unit' }).click();
  await page4.getByRole('gridcell', { name: ' Select' }).click();
  await page4.getByRole('link', { name: ' New' }).click();
  await page4.locator('#unitcode').click();
  await page4.locator('#unitcode').fill('M02');
  await page4.getByText('Unit Name : *').click();
  await page4.locator('#unitname').click();
  await page4.locator('#unitname').fill('M02');
  await page4.locator('#valid_from').fill('2024-06-01');
  await page4.locator('#valid_to').fill('2024-08-31');
  await page4.locator('#u_type').selectOption('MD1');
  await page4.getByRole('button', { name: '' }).first().click();
  await page4.getByText('SELECT').click();
  await page4.getByRole('button', { name: '' }).nth(1).click();
  await page4.locator('#DataTables_Table_1').getByText('SELECT').click();
  await page4.locator('#SellingArea').click();
  await page4.locator('#SellingArea').fill('48');
  await page4.locator('#AssetType').selectOption('2');
  await page4.locator('#AssetType').selectOption('4');
  await page4.getByText('Save').click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Project Unit' }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('link', { name: ' New' }).click();
  await page4.locator('#unitcode').click();
  await page4.locator('#unitcode').fill('M03');
  await page4.locator('#unitname').click();
  await page4.locator('#unitname').fill('M03');
  await page4.locator('#valid_from').fill('2024-06-01');
  await page4.locator('#valid_to').fill('2024-07-31');
  await page4.locator('#u_type').selectOption('MD1');
  await page4.getByRole('button', { name: '' }).first().click();
  await page4.getByText('SELECT').click();
  await page4.getByRole('button', { name: '' }).nth(1).click();
  await page4.locator('#DataTables_Table_1').getByText('SELECT').click();
  await page4.locator('#SellingArea').click();
  await page4.locator('#SellingArea').click();
  await page4.locator('#SellingArea').fill('65');
  await page4.getByText('Save').click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.goto('https://maison-cm-test.iconframework.com/data_master/setup_project_block/1/1/253');
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('link', { name: '' }).click();
  await page4.getByRole('link', { name: ' Setup Block / Floor' }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('link', { name: '' }).click();
  await page4.locator('#del1173').click();
  await page4.getByRole('button', { name: 'Yes, delete it!' }).click(); 
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.locator('#del1172').click();
  await page4.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();

  await page4.locator('#del1171').click();
  await page4.getByRole('button', { name: 'Yes, delete it!' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('button', { name: ' Save' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.locator('#select0000001012').click();
  await page4.locator('#select0000001013').click();
  await page4.getByRole('button', { name: 'Select' }).click();
  await page4.getByRole('button', { name: ' Save' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByRole('link', { name: ' Setup Block / Floor' }).click();
  await page4.getByRole('link', { name: ' Setup Position' }).click();
  await page4.getByRole('button', { name: ' Add' }).click();
  await page4.locator('#p_code').click();
  await page4.locator('#p_code').fill('M-Test');
  await page4.locator('#p_name').click();
  await page4.locator('#p_name').fill('M-Test');
  await page4.locator('#remark').click();
  await page4.locator('#remark').fill('M-Test');
  await page4.getByRole('button', { name: ' Save' }).click();
  await page4.getByRole('button', { name: 'OK' }).click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('m');
  await page4.getByRole('link', { name: ' Setup Project Unit' }).click();
  await page4.getByRole('gridcell', { name: ' Select' }).click();
  await page4.getByRole('row', { name: 'M01 M01 Active ' }).getByRole('link').click();
  await page4.getByRole('link', { name: ' Setup Group Model Type' }).click();
  await page4.getByRole('link', { name: ' Setup Model Type' }).click();
  await page4.getByRole('link', { name: ' Setup Project Unit' }).click();
  await page4.getByRole('link', { name: ' Select' }).click();
  await page4.getByRole('link', { name: ' Setup Permission' }).click();
  await page4.getByRole('link', { name: ' Permission by User' }).click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('m');
  await page4.locator('#data94').click();
  await page4.locator('#ic_per94').getByText('Show PO Recieve Amount').click();
  await page4.locator('#ic_chk94').check();
  await page4.getByRole('button', { name: ' Close' }).click();
  await page4.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).getByRole('link').click();
  await page4.getByPlaceholder('Type to filter...').click();
  await page4.getByPlaceholder('Type to filter...').fill('m');
  const page5Promise = page4.waitForEvent('popup');
  await page4.getByRole('row', { name: '14 Mtest Mtest 10/06/2024 14:' }).locator('#modalcompany').click();
  const page5 = await page5Promise;
  await page5.getByRole('button', { name: 'Department' }).click();
  await page5.getByRole('button', { name: 'Project' }).click();
  await page5.locator('a').filter({ hasText: 'Genaral Settings' }).click();
  await page5.getByRole('link', { name: ' Setup Document Numbering' }).click();
  await page5.getByRole('row', { name: '1 Business Partners - Vendor' }).getByRole('link').click();
  await page5.getByRole('row', { name: '2 Business Partners -' }).getByRole('link').click();
  await page5.getByRole('row', { name: 'User ( All Company )  OPEN' }).getByRole('link').click();
  await page5.getByRole('row', { name: '3 Item Master Data ( All' }).getByRole('link').click();
  await page5.locator('a').filter({ hasText: 'Cost Control' }).click();
  await page5.getByRole('link', { name: ' Setup Cost Center' }).click();
});